<?php

namespace Database\Seeders;

use App\Models\Surah;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $surahs = [
            ['name'=>'Al-Fatihah', 'number'=>1, 'varse_count'=>7, 'juz_number'=>1, 'meaning'=>'Pembuka', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Baqarah', 'number'=>2, 'varse_count'=>286, 'juz_number'=>1, 'meaning'=>'Sapi Betina', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ali Imran', 'number'=>3, 'varse_count'=>200, 'juz_number'=>3, 'meaning'=>'Keluarga Imran', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Nisa', 'number'=>4,  'varse_count'=>176, 'juz_number'=>4,  'meaning'=>'Wanita',                   'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ma\'idah', 'number'=>5,  'varse_count'=>120, 'juz_number'=>6,  'meaning'=>'Hidangan',                 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-An\'am', 'number'=>6,  'varse_count'=>165, 'juz_number'=>7,  'meaning'=>'Binatang Ternak',          'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-A\'raf', 'number'=>7,  'varse_count'=>206, 'juz_number'=>8,  'meaning'=>'Tempat Tertinggi',         'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Anfal', 'number'=>8,  'varse_count'=>75, 'juz_number'=>9,  'meaning'=>'Rampasan Perang',          'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Taubah', 'number'=>9,  'varse_count'=>129, 'juz_number'=>10, 'meaning'=>'Pengampunan',              'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Yunus',  'number'=>10, 'varse_count'=>109, 'juz_number'=>11, 'meaning'=>'Nabi Yunus',               'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Hud', 'number'=>11, 'varse_count'=>123, 'juz_number'=>11, 'meaning'=>'Nabi Hud',                 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Yusuf', 'number'=>12, 'varse_count'=>111, 'juz_number'=>12, 'meaning'=>'Nabi Yusuf',               'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ar-Ra\'d', 'number'=>13, 'varse_count'=>43, 'juz_number'=>13, 'meaning'=>'Guruh',                    'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ibrahim', 'number'=>14, 'varse_count'=>52, 'juz_number'=>13, 'meaning'=>'Nabi Ibrahim',             'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Hijr', 'number'=>15, 'varse_count'=>99,  'juz_number'=>14, 'meaning'=>'Gunung Hijr',              'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Nahl', 'number'=>16, 'varse_count'=>128, 'juz_number'=>14, 'meaning'=>'Lebah',                    'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Isra\'', 'number'=>17, 'varse_count'=>111, 'juz_number'=>15, 'meaning'=>'Perjalanan Malam',         'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Kahf', 'number'=>18, 'varse_count'=>110, 'juz_number'=>15, 'meaning'=>'Gua',                      'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Maryam', 'number'=>19, 'varse_count'=>98,  'juz_number'=>16, 'meaning'=>'Maryam',                   'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ta Ha', 'number'=>20, 'varse_count'=>135, 'juz_number'=>16, 'meaning'=>'Ta Ha',                    'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Anbiya', 'number'=>21, 'varse_count'=>112, 'juz_number'=>17, 'meaning'=>'Para Nabi', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Hajj', 'number'=>22, 'varse_count'=>78, 'juz_number'=>17, 'meaning'=>'Haji', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Mu\'minun', 'number'=>23, 'varse_count'=>118, 'juz_number'=>18, 'meaning'=>'Orang-Orang Mukmin', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Nur', 'number'=>24, 'varse_count'=>64, 'juz_number'=>18, 'meaning'=>'Cahaya', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Furqan', 'number'=>25, 'varse_count'=>77, 'juz_number'=>19, 'meaning'=>'Pembeda', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Asy-Syu\'ara', 'number'=>26, 'varse_count'=>227, 'juz_number'=>19, 'meaning'=>'Penyair', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Naml', 'number'=>27, 'varse_count'=>93, 'juz_number'=>19, 'meaning'=>'Semut', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Qasas', 'number'=>28, 'varse_count'=>88, 'juz_number'=>20, 'meaning'=>'Kisah-Kisah', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ankabut', 'number'=>29, 'varse_count'=>69, 'juz_number'=>20, 'meaning'=>'Laba-Laba', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ar-Rum', 'number'=>30, 'varse_count'=>60, 'juz_number'=>21, 'meaning'=>'Bangsa Romawi', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Luqman', 'number'=>31, 'varse_count'=>34, 'juz_number'=>21, 'meaning'=>'Luqman', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'As-Sajdah', 'number'=>32, 'varse_count'=>30, 'juz_number'=>21, 'meaning'=>'Sujud', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ahzab', 'number'=>33, 'varse_count'=>73, 'juz_number'=>21, 'meaning'=>'Golongan yang Bersekutu', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Saba\'', 'number'=>34, 'varse_count'=>54, 'juz_number'=>22, 'meaning'=>'Kaum Saba\'', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Fatir', 'number'=>35, 'varse_count'=>45, 'juz_number'=>22, 'meaning'=>'Pencipta', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Yasin', 'number'=>36, 'varse_count'=>83, 'juz_number'=>22, 'meaning'=>'Yasin', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'As-Saffat', 'number'=>37, 'varse_count'=>182, 'juz_number'=>23, 'meaning'=>'Barisan-Barisan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Sad', 'number'=>38, 'varse_count'=>88, 'juz_number'=>23, 'meaning'=>'Sad', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Az-Zumar', 'number'=>39, 'varse_count'=>75, 'juz_number'=>23, 'meaning'=>'Rombongan-Rombongan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ghafir', 'number'=>40, 'varse_count'=>85, 'juz_number'=>24, 'meaning'=>'Yang Maha Pengampun', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Fussilat', 'number'=>41, 'varse_count'=>54, 'juz_number'=>24, 'meaning'=>'Yang Dijelaskan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Asy-Syura', 'number'=>42, 'varse_count'=>53, 'juz_number'=>25, 'meaning'=>'Musyawarah', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Az-Zukhruf', 'number'=>43, 'varse_count'=>89, 'juz_number'=>25, 'meaning'=>'Perhiasan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ad-Dukhan', 'number'=>44, 'varse_count'=>59, 'juz_number'=>25, 'meaning'=>'Kabut', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Jasiyah', 'number'=>45, 'varse_count'=>37, 'juz_number'=>25, 'meaning'=>'Yang Berlutut', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ahqaf', 'number'=>46, 'varse_count'=>35, 'juz_number'=>26, 'meaning'=>'Bukit-Bukit Pasir', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Muhammad', 'number'=>47, 'varse_count'=>38, 'juz_number'=>26, 'meaning'=>'Nabi Muhammad', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Fath', 'number'=>48, 'varse_count'=>29, 'juz_number'=>26, 'meaning'=>'Kemenangan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Hujurat', 'number'=>49, 'varse_count'=>18, 'juz_number'=>26, 'meaning'=>'Kamar-Kamar', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Qaf', 'number'=>50, 'varse_count'=>45, 'juz_number'=>26, 'meaning'=>'Qaf', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Adz-Dzariyat', 'number'=>51, 'varse_count'=>60, 'juz_number'=>26, 'meaning'=>'Angin yang Menerbangkan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Tur', 'number'=>52, 'varse_count'=>49, 'juz_number'=>27, 'meaning'=>'Bukit', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Najm', 'number'=>53, 'varse_count'=>62, 'juz_number'=>27, 'meaning'=>'Bintang', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Qamar', 'number'=>54, 'varse_count'=>55, 'juz_number'=>27, 'meaning'=>'Bulan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ar-Rahman', 'number'=>55, 'varse_count'=>78, 'juz_number'=>27, 'meaning'=>'Yang Maha Pengasih', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Waqi\'ah', 'number'=>56, 'varse_count'=>96, 'juz_number'=>27, 'meaning'=>'Hari Kiamat', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Hadid', 'number'=>57, 'varse_count'=>29, 'juz_number'=>27, 'meaning'=>'Besi', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Mujadilah', 'number'=>58, 'varse_count'=>22, 'juz_number'=>28, 'meaning'=>'Wanita yang Menggugat', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Hasyr', 'number'=>59, 'varse_count'=>24, 'juz_number'=>28, 'meaning'=>'Pengusiran', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Mumtahanah', 'number'=>60, 'varse_count'=>13, 'juz_number'=>28, 'meaning'=>'Wanita yang Diuji', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'As-Saff', 'number'=>61, 'varse_count'=>14, 'juz_number'=>28, 'meaning'=>'Barisan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Jumu\'ah', 'number'=>62, 'varse_count'=>11, 'juz_number'=>28, 'meaning'=>'Jumat', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Munafiqun', 'number'=>63, 'varse_count'=>11, 'juz_number'=>28, 'meaning'=>'Orang-Orang Munafik', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Taghabun', 'number'=>64, 'varse_count'=>18, 'juz_number'=>28, 'meaning'=>'Hari Ditampakkan Kesalahan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Talaq', 'number'=>65, 'varse_count'=>12, 'juz_number'=>28, 'meaning'=>'Talak', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Tahrim', 'number'=>66, 'varse_count'=>12, 'juz_number'=>28, 'meaning'=>'Pengharaman', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Mulk', 'number'=>67, 'varse_count'=>30, 'juz_number'=>29, 'meaning'=>'Kerajaan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Qalam', 'number'=>68, 'varse_count'=>52, 'juz_number'=>29, 'meaning'=>'Pena', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Haqqah', 'number'=>69, 'varse_count'=>52, 'juz_number'=>29, 'meaning'=>'Hari Kebenaran', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ma\'arij', 'number'=>70, 'varse_count'=>44, 'juz_number'=>29, 'meaning'=>'Tempat Naik', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Nuh', 'number'=>71, 'varse_count'=>28, 'juz_number'=>29, 'meaning'=>'Nabi Nuh', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Jinn', 'number'=>72, 'varse_count'=>28, 'juz_number'=>29, 'meaning'=>'Jin', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Muzzammil', 'number'=>73, 'varse_count'=>20, 'juz_number'=>29, 'meaning'=>'Orang yang Berselimut', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Muddassir', 'number'=>74, 'varse_count'=>56, 'juz_number'=>29, 'meaning'=>'Orang yang Berkemul', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Qiyamah', 'number'=>75, 'varse_count'=>40, 'juz_number'=>29, 'meaning'=>'Kiamat', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Insan', 'number'=>76, 'varse_count'=>31, 'juz_number'=>29, 'meaning'=>'Manusia', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Mursalat', 'number'=>77, 'varse_count'=>50, 'juz_number'=>29, 'meaning'=>'Malaikat yang Diutus', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Naba', 'number'=>78, 'varse_count'=>40, 'juz_number'=>30, 'meaning'=>'Berita Besar', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Nazi\'at', 'number'=>79, 'varse_count'=>46, 'juz_number'=>30, 'meaning'=>'Malaikat yang Mencabut', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Abasa', 'number'=>80, 'varse_count'=>42, 'juz_number'=>30, 'meaning'=>'Ia Bermuka Masam', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Takwir', 'number'=>81, 'varse_count'=>29, 'juz_number'=>30, 'meaning'=>'Menggulung', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Infitar', 'number'=>82, 'varse_count'=>19, 'juz_number'=>30, 'meaning'=>'Terbelah', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Mutaffifin', 'number'=>83, 'varse_count'=>36, 'juz_number'=>30, 'meaning'=>'Orang yang Curang', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Insyiqaq', 'number'=>84, 'varse_count'=>25, 'juz_number'=>30, 'meaning'=>'Terbelah', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Buruj', 'number'=>85, 'varse_count'=>22, 'juz_number'=>30, 'meaning'=>'Gugusan Bintang', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Tariq', 'number'=>86, 'varse_count'=>17, 'juz_number'=>30, 'meaning'=>'Yang Datang di Malam Hari', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-A\'la', 'number'=>87, 'varse_count'=>19, 'juz_number'=>30, 'meaning'=>'Yang Maha Tinggi', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ghasyiyah', 'number'=>88, 'varse_count'=>26, 'juz_number'=>30, 'meaning'=>'Hari yang Menggelisahkan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Fajr', 'number'=>89, 'varse_count'=>30, 'juz_number'=>30, 'meaning'=>'Fajar', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Balad', 'number'=>90, 'varse_count'=>20, 'juz_number'=>30, 'meaning'=>'Negeri', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Asy-Syams', 'number'=>91, 'varse_count'=>15, 'juz_number'=>30, 'meaning'=>'Matahari', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Lail', 'number'=>92, 'varse_count'=>21, 'juz_number'=>30, 'meaning'=>'Malam', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Ad-Duha', 'number'=>93, 'varse_count'=>11, 'juz_number'=>30, 'meaning'=>'Waktu Dhuha', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Asy-Syarh', 'number'=>94, 'varse_count'=>8, 'juz_number'=>30, 'meaning'=>'Melapangkan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Tin', 'number'=>95, 'varse_count'=>8, 'juz_number'=>30, 'meaning'=>'Buah Tin', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-\'Alaq', 'number'=>96, 'varse_count'=>19, 'juz_number'=>30, 'meaning'=>'Segumpal Darah', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Qadr', 'number'=>97, 'varse_count'=>5, 'juz_number'=>30, 'meaning'=>'Kemuliaan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Bayyinah', 'number'=>98, 'varse_count'=>8, 'juz_number'=>30, 'meaning'=>'Bukti yang Nyata', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Az-Zalzalah', 'number'=>99, 'varse_count'=>8, 'juz_number'=>30, 'meaning'=>'Guncangan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-\'Adiyat', 'number'=>100, 'varse_count'=>11, 'juz_number'=>30, 'meaning'=>'Kuda Perang', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Qari\'ah', 'number'=>101, 'varse_count'=>11, 'juz_number'=>30, 'meaning'=>'Hari Kegoncangan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'At-Takasur', 'number'=>102, 'varse_count'=>8, 'juz_number'=>30, 'meaning'=>'Bermegah-Megahan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-\'Asr', 'number'=>103, 'varse_count'=>3, 'juz_number'=>30, 'meaning'=>'Waktu', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Humazah', 'number'=>104, 'varse_count'=>9, 'juz_number'=>30, 'meaning'=>'Pengumpat', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Fil', 'number'=>105, 'varse_count'=>5, 'juz_number'=>30, 'meaning'=>'Gajah', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Quraisy', 'number'=>106, 'varse_count'=>4, 'juz_number'=>30, 'meaning'=>'Suku Quraisy', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ma\'un', 'number'=>107, 'varse_count'=>7, 'juz_number'=>30, 'meaning'=>'Barang yang Berguna', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Kautsar', 'number'=>108, 'varse_count'=>3, 'juz_number'=>30, 'meaning'=>'Nikmat yang Banyak', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Kafirun', 'number'=>109, 'varse_count'=>6, 'juz_number'=>30, 'meaning'=>'Orang-Orang Kafir', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Nasr', 'number'=>110, 'varse_count'=>3, 'juz_number'=>30, 'meaning'=>'Pertolongan', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Lahab', 'number'=>111, 'varse_count'=>5, 'juz_number'=>30, 'meaning'=>'Gejolak Api', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Ikhlas', 'number'=>112, 'varse_count'=>4, 'juz_number'=>30, 'meaning'=>'Ikhlas', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'Al-Falaq', 'number'=>113, 'varse_count'=>5, 'juz_number'=>30, 'meaning'=>'Waktu Subuh', 'created_at'=>$now, 'updated_at'=>$now],
            ['name'=>'An-Nas', 'number'=>114, 'varse_count'=>6, 'juz_number'=>30, 'meaning'=>'Manusia', 'created_at'=>$now, 'updated_at'=>$now],
        ];

        Surah::insert($surahs);
    }
}
